export const expectativas = [
  {
    id: 1,
    nombre: "Todos los nuevos procesos incluidos perifericos",
    evidencia: "Documento",
    prioridad: "P1",
    ponderacion: "1",
    comentarios:
      "Se finalizo el formato para el llenado, en espera de validar la forma de aplicar y realizar el proceso con gerencia de UEN Energia, dar de alta formato en control de documentos.",
  },
  {
    id: 2,
    nombre: "Manejo de materiales",
    evidencia: "Documento",
    prioridad: "P1",
    ponderacion: "1",
    comentarios:
      "Cotización para realizar estudio, contacto con Baldemar para la persona que realizo el analisis en multipak. En espera de la actualización de la propuesta economica.",
  },
  {
    id: 3,
    nombre: "Documento de IPERCON",
    evidencia: "Documento",
    prioridad: "P1",
    ponderacion: "2",
    comentarios:
      "Carga de  informarción pasar el formato de IPERCON FSEG 023, finalizando el ART.",
  },
];

export const avanceEntrable = [
  {
    id: 1,
    idEntregable: 1,
    idMaquina: 1,
    idFase: 1,
    nombreMaquina: "Extruder 4.5",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "",
  },
  {
    id: 2,
    idEntregable: 1,
    idMaquina: 2,
    idFase: 1,
    nombreMaquina: "Buncher 1800",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "",
  },
  {
    id: 3,
    idEntregable: 1,
    idMaquina: 3,
    idFase: 1,
    nombreMaquina: "B T 3+1",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "",
  },
  {
    id: 4,
    idEntregable: 1,
    idMaquina: 4,
    idFase: 1,
    nombreMaquina: "MSM86",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "",
  },
  {
    id: 5,
    idEntregable: 1,
    idMaquina: 5,
    idFase: 1,
    nombreMaquina: "C. Strander",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "No se tiene datos de los equipos",
  },
  {
    id: 6,
    idEntregable: 1,
    idMaquina: 6,
    idFase: 1,
    nombreMaquina: "C. Compound",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "",
  },
  {
    id: 7,
    idEntregable: 1,
    idMaquina: 7,
    idFase: 1,
    nombreMaquina: "P. Electricas",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "",
  },
  {
    id: 8,
    idEntregable: 1,
    idMaquina: 8,
    idFase: 1,
    nombreMaquina: "Med 2da mano",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "",
  },
  {
    id: 9,
    idEntregable: 1,
    idMaquina: 9,
    idFase: 1,
    nombreMaquina: "Coiler 2da mano",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "",
  },
  {
    id: 10,
    idEntregable: 1,
    idMaquina: 10,
    idFase: 1,
    nombreMaquina: "Tulsa Power",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "Mismo formato de ART",
  },
  {
    id: 11,
    idEntregable: 1,
    idMaquina: 11,
    idFase: 1,
    nombreMaquina: "Caballe",
    responsable: "Juan Perez",
    fecha_inicio: "2021-02-15",
    fecha_termino: "2021-03-02",
    fecha_real: "2021-03-02",
    avance: 100,
    comentarios: "Mismo formato de ART",
  },
];
